name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff mypy pytest pytest-cov numpy soundfile build
      - name: Lint
        run: |
          ruff OcchioOnniveggente/src scripts
          black --check OcchioOnniveggente/src scripts
      - name: Type check
        run: mypy OcchioOnniveggente/src scripts
      - name: Run tests
        run: >-
          pytest tests/test_local_audio_interfaces.py
          tests/test_retrieval_basic.py
          tests/test_ui_state_chat.py -q
      - name: Build package
        run: python -m build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
