name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools-scm
      - name: Build package
        run: python -m build
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
