name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pytest pytest-cov numpy soundfile
      - name: Run tests
        run: >-
          pytest tests/test_local_audio_interfaces.py
          tests/test_retrieval_basic.py
          tests/test_ui_state_chat.py
          --cov=OcchioOnniveggente/src --cov-report=term --cov-report=xml
          --cov-fail-under=5 -q
